// Internationalization (i18n) Module

const translations = {
  ko: {
    // Header
    siteTitle: 'Security Reports',
    siteSubtitle: 'AI 기반 보안 스캔 리포트',
    
    // Navigation
    navHome: '홈',
    navReports: '리포트',
    
    // Buttons
    btnLanguage: '언어',
    btnTheme: '테마',
    btnDark: '다크',
    btnLight: '라이트',
    
    // Welcome Section
    welcomeTitle: 'AI 보안 스캔 리포트에 오신 것을 환영합니다',
    welcomeSubtitle: '프로젝트의 보안 취약점을 AI로 분석하고, 상세한 리포트를 확인하세요',
    
    // Instructions Section
    instructionsTitle: '시작하기',
    instructionsSubtitle: 'AI 보안 스캔을 시작하려면 아래 단계를 따라주세요',
    
    step1Title: '1. AI 프롬프트 다운로드',
    step1Desc: '사용할 AI(Claude, Gemini 등)를 선택하고 보안 스캔 프롬프트를 다운로드하세요',
    
    step2Title: '2. 프로젝트 스캔',
    step2Desc: '다운로드한 프롬프트를 AI에 적용하여 프로젝트를 스캔하세요',
    
    step3Title: '3. 리포트 확인',
    step3Desc: 'AI가 생성한 JSON 결과를 리포트 탭에서 업로드하여 확인하세요',
    
    // Filter Section
    filterLabel: 'AI 선택:',
    filterAll: '전체',
    filterClaude: 'Claude',
    filterGemini: 'Gemini',
    
    // Footer
    footerText: '© 2026 Security Reports. 오픈소스 프로젝트',
    footerGithub: 'GitHub에서 보기',
    
    // Coming Soon
    comingSoon: '곧 출시 예정',
  },
  
  en: {
    // Header
    siteTitle: 'Security Reports',
    siteSubtitle: 'AI-Powered Security Scan Reports',
    
    // Navigation
    navHome: 'Home',
    navReports: 'Reports',
    
    // Buttons
    btnLanguage: 'Language',
    btnTheme: 'Theme',
    btnDark: 'Dark',
    btnLight: 'Light',
    
    // Welcome Section
    welcomeTitle: 'Welcome to AI Security Scan Reports',
    welcomeSubtitle: 'Analyze your project\'s security vulnerabilities with AI and view detailed reports',
    
    // Instructions Section
    instructionsTitle: 'Getting Started',
    instructionsSubtitle: 'Follow these steps to begin your AI security scan',
    
    step1Title: '1. Download AI Prompt',
    step1Desc: 'Select your AI (Claude, Gemini, etc.) and download the security scan prompt',
    
    step2Title: '2. Scan Your Project',
    step2Desc: 'Apply the downloaded prompt to your AI and scan your project',
    
    step3Title: '3. View Report',
    step3Desc: 'Upload the JSON result generated by AI in the Reports tab',
    
    // Filter Section
    filterLabel: 'Select AI:',
    filterAll: 'All',
    filterClaude: 'Claude',
    filterGemini: 'Gemini',
    
    // Footer
    footerText: '© 2026 Security Reports. Open Source Project',
    footerGithub: 'View on GitHub',
    
    // Coming Soon
    comingSoon: 'Coming Soon',
  }
};

class I18n {
  constructor() {
    this.currentLang = this.loadLanguage();
    this.translations = translations;
  }
  
  loadLanguage() {
    // Check localStorage first
    const saved = localStorage.getItem('language');
    if (saved && (saved === 'ko' || saved === 'en')) {
      return saved;
    }
    
    // Detect browser language
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith('ko')) {
      return 'ko';
    }
    
    return 'en'; // Default to English
  }
  
  setLanguage(lang) {
    if (lang !== 'ko' && lang !== 'en') {
      console.error('Unsupported language:', lang);
      return;
    }
    
    this.currentLang = lang;
    localStorage.setItem('language', lang);
    this.updatePageLanguage();
  }
  
  toggleLanguage() {
    const newLang = this.currentLang === 'ko' ? 'en' : 'ko';
    this.setLanguage(newLang);
  }
  
  t(key) {
    return this.translations[this.currentLang][key] || key;
  }
  
  updatePageLanguage() {
    // Update all elements with data-i18n attribute
    document.querySelectorAll('[data-i18n]').forEach(element => {
      const key = element.getAttribute('data-i18n');
      const translation = this.t(key);
      
      // Check if element has a placeholder
      if (element.hasAttribute('placeholder')) {
        element.setAttribute('placeholder', translation);
      } else {
        element.textContent = translation;
      }
    });
    
    // Update language button text
    const langBtn = document.getElementById('languageBtn');
    if (langBtn) {
      const langText = langBtn.querySelector('.btn-text');
      if (langText) {
        langText.textContent = this.currentLang === 'ko' ? 'EN' : 'KO';
      }
    }
    
    // Update HTML lang attribute
    document.documentElement.lang = this.currentLang;
  }
}

// Export for use in other scripts
window.i18n = new I18n();
